name: github actions discord secretes 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get the time
        id: time
        run : |
          NOW=$(date)
          echo "now=${NOW}" >> $GITHUB_OUTPUT
        env:
          TZ : Europe/Madrid
      - name: Send the time
        uses: Satak/webrequest-action@v1.2.3
        with:
          url: ${{ secrets.DISCORD_GITHUB_ACTIONS_CHANNEL_WEBHOOK }}
          method: POST
          payload: '{ "content": "The workflow ran at ${{steps.time.outputs.now}}!" }'
            

